"""
Submission reading and validation, copied verbatim from the evaluation script.
================================================================================
These four functions are the ones the leaderboard uses to read and validate a
submission (``read_submission`` and ``parse_predictions``, with their helpers),
lifted unchanged from the challenge's ``evaluation_script/main.py``. The format
checker calls them, so an error it reports is the error the platform reports.

Do not edit this file. If the evaluation script changes, copy it again.
"""

from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

MAX_CHARS = 5000


def _read_jsonl_bytes(data: bytes, fname: str) -> list[dict]:
    rows = []
    for i, line in enumerate(data.decode("utf-8-sig").splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as e:
            raise ValueError(f"{fname}:{i}: invalid JSON ({e.msg})") from None
        if not isinstance(obj, dict):
            raise ValueError(f"{fname}:{i}: each line must be a JSON object")
        rows.append(obj)
    if not rows:
        raise ValueError(f"{fname}: file is empty")
    return rows


def read_submission(path: str) -> tuple[list[dict], str]:
    p = Path(path)
    data = p.read_bytes()
    if zipfile.is_zipfile(io.BytesIO(data)):
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            names = [n for n in zf.namelist() if n.endswith(".jsonl") and "__MACOSX" not in n and not Path(n).name.startswith("._")]
            if not names:
                raise ValueError(f"the zip must contain prediction.jsonl (found: {zf.namelist()[:10]})")
            pref = [n for n in names if Path(n).name == "prediction.jsonl"]
            name = pref[0] if pref else names[0]
            return _read_jsonl_bytes(zf.read(name), Path(name).name), Path(name).name
    text = data.decode("utf-8-sig").lstrip()
    if text.startswith("["):
        rows = json.loads(text)
        if not isinstance(rows, list) or not all(isinstance(r, dict) for r in rows):
            raise ValueError("a .json submission must be a list of objects")
        return rows, p.name
    return _read_jsonl_bytes(data, p.name), p.name


def _clean(x) -> str:
    if x is None:
        return ""
    if not isinstance(x, str):
        x = str(x)
    return x.strip()[:MAX_CHARS]


def parse_predictions(rows: list[dict], gold_ids: set[str], langs: list[str], fname: str) -> dict[str, dict[str, str]]:
    preds: dict[str, dict[str, str]] = {}
    seen: set[tuple[str, str]] = set()
    nested_ids: set[str] = set()
    for i, r in enumerate(rows, 1):
        if "id" not in r:
            raise ValueError(f"{fname}:{i}: missing key 'id'")
        rid = str(r["id"]).strip()
        if not rid:
            raise ValueError(f"{fname}:{i}: empty id")
        if "answers" in r:
            ans = r["answers"]
            if not isinstance(ans, dict):
                raise ValueError(f"{fname}:{i}: 'answers' must be an object mapping language -> answer")
            bad = sorted(set(ans) - set(langs))
            if bad:
                raise ValueError(f"{fname}:{i}: unknown language key(s) {bad}; this phase scores {langs}")
            if rid in nested_ids:
                raise ValueError(f"{fname}:{i}: duplicate id {rid!r}")
            nested_ids.add(rid)
            d = preds.setdefault(rid, {})
            for l, a in ans.items():
                if (rid, l) in seen:
                    raise ValueError(f"{fname}:{i}: duplicate answer for id {rid!r} language {l!r}")
                seen.add((rid, l)); d[l] = _clean(a)
        elif "lang" in r or "answer" in r:
            l = str(r.get("lang", "")).strip().lower()
            if l not in langs:
                raise ValueError(f"{fname}:{i}: 'lang' must be one of {langs} (got {r.get('lang')!r})")
            if (rid, l) in seen:
                raise ValueError(f"{fname}:{i}: duplicate answer for id {rid!r} language {l!r}")
            seen.add((rid, l)); preds.setdefault(rid, {})[l] = _clean(r.get("answer"))
        else:
            raise ValueError(f"{fname}:{i}: each line needs 'id' + 'answers' (object) or 'id' + 'lang' + 'answer'")
    missing, extra = gold_ids - set(preds), set(preds) - gold_ids
    if missing or extra:
        raise ValueError(
            f"id mismatch with the gold set: missing={len(missing)} (e.g. {sorted(missing)[:5]}), "
            f"unknown={len(extra)} (e.g. {sorted(extra)[:5]}). Submit exactly one entry for each of the "
            f"{len(gold_ids)} ids in the public file.")
    return preds
